site_name: envas（エンバス） お知らせサイト
site_description: WEB 席次表 envas（エンバス） お知らせサイトです。
site_author: envas
site_url: https://info.envas.jp/
copyright: "&copy; 2025 WISH LLC. All rights reserved."

theme:
  name: material
  logo: images/envas.png
  favicon: images/favicon.ico
  language: ja
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.top

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: "ja"
  - rss:
      match_path: ".*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - tags
      feeds_filenames:
        rss_created: feed.xml
      json_feed_enabled: false

extra:
  generator: false
  social:
    - icon: fontawesome/solid/rss
      link: /feed.xml
      name: RSS フィード

nav:
  - ホーム: index.md
  - RSS: /feed.xml

markdown_extensions:
  - nl2br
